/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-07-08 17:28:43 UTC)
 * on 2016-09-25 at 17:25:05 UTC 
 * Modify at your own risk.
 */

package com.wgappbackend.plannedeventendpoint;

/**
 * Service definition for Plannedeventendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PlannedeventendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Plannedeventendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the plannedeventendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "plannedeventendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Plannedeventendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Plannedeventendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPlannedEvent".
   *
   * This request holds the parameters needed by the plannedeventendpoint server.  After setting any
   * optional parameters, call the {@link GetPlannedEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetPlannedEvent getPlannedEvent(java.lang.Long id) throws java.io.IOException {
    GetPlannedEvent result = new GetPlannedEvent(id);
    initialize(result);
    return result;
  }

  public class GetPlannedEvent extends PlannedeventendpointRequest<com.wgappbackend.plannedeventendpoint.model.PlannedEvent> {

    private static final String REST_PATH = "plannedevent/{id}";

    /**
     * Create a request for the method "getPlannedEvent".
     *
     * This request holds the parameters needed by the the plannedeventendpoint server.  After setting
     * any optional parameters, call the {@link GetPlannedEvent#execute()} method to invoke the remote
     * operation. <p> {@link GetPlannedEvent#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPlannedEvent(java.lang.Long id) {
      super(Plannedeventendpoint.this, "GET", REST_PATH, null, com.wgappbackend.plannedeventendpoint.model.PlannedEvent.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPlannedEvent setAlt(java.lang.String alt) {
      return (GetPlannedEvent) super.setAlt(alt);
    }

    @Override
    public GetPlannedEvent setFields(java.lang.String fields) {
      return (GetPlannedEvent) super.setFields(fields);
    }

    @Override
    public GetPlannedEvent setKey(java.lang.String key) {
      return (GetPlannedEvent) super.setKey(key);
    }

    @Override
    public GetPlannedEvent setOauthToken(java.lang.String oauthToken) {
      return (GetPlannedEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPlannedEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPlannedEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPlannedEvent setQuotaUser(java.lang.String quotaUser) {
      return (GetPlannedEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPlannedEvent setUserIp(java.lang.String userIp) {
      return (GetPlannedEvent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPlannedEvent setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPlannedEvent set(String parameterName, Object value) {
      return (GetPlannedEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPlannedEvent".
   *
   * This request holds the parameters needed by the plannedeventendpoint server.  After setting any
   * optional parameters, call the {@link InsertPlannedEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.plannedeventendpoint.model.PlannedEvent}
   * @return the request
   */
  public InsertPlannedEvent insertPlannedEvent(com.wgappbackend.plannedeventendpoint.model.PlannedEvent content) throws java.io.IOException {
    InsertPlannedEvent result = new InsertPlannedEvent(content);
    initialize(result);
    return result;
  }

  public class InsertPlannedEvent extends PlannedeventendpointRequest<com.wgappbackend.plannedeventendpoint.model.PlannedEvent> {

    private static final String REST_PATH = "plannedevent";

    /**
     * Create a request for the method "insertPlannedEvent".
     *
     * This request holds the parameters needed by the the plannedeventendpoint server.  After setting
     * any optional parameters, call the {@link InsertPlannedEvent#execute()} method to invoke the
     * remote operation. <p> {@link InsertPlannedEvent#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.plannedeventendpoint.model.PlannedEvent}
     * @since 1.13
     */
    protected InsertPlannedEvent(com.wgappbackend.plannedeventendpoint.model.PlannedEvent content) {
      super(Plannedeventendpoint.this, "POST", REST_PATH, content, com.wgappbackend.plannedeventendpoint.model.PlannedEvent.class);
    }

    @Override
    public InsertPlannedEvent setAlt(java.lang.String alt) {
      return (InsertPlannedEvent) super.setAlt(alt);
    }

    @Override
    public InsertPlannedEvent setFields(java.lang.String fields) {
      return (InsertPlannedEvent) super.setFields(fields);
    }

    @Override
    public InsertPlannedEvent setKey(java.lang.String key) {
      return (InsertPlannedEvent) super.setKey(key);
    }

    @Override
    public InsertPlannedEvent setOauthToken(java.lang.String oauthToken) {
      return (InsertPlannedEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPlannedEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPlannedEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPlannedEvent setQuotaUser(java.lang.String quotaUser) {
      return (InsertPlannedEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPlannedEvent setUserIp(java.lang.String userIp) {
      return (InsertPlannedEvent) super.setUserIp(userIp);
    }

    @Override
    public InsertPlannedEvent set(String parameterName, Object value) {
      return (InsertPlannedEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPlannedEvent".
   *
   * This request holds the parameters needed by the plannedeventendpoint server.  After setting any
   * optional parameters, call the {@link ListPlannedEvent#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPlannedEvent listPlannedEvent() throws java.io.IOException {
    ListPlannedEvent result = new ListPlannedEvent();
    initialize(result);
    return result;
  }

  public class ListPlannedEvent extends PlannedeventendpointRequest<com.wgappbackend.plannedeventendpoint.model.CollectionResponsePlannedEvent> {

    private static final String REST_PATH = "plannedevent";

    /**
     * Create a request for the method "listPlannedEvent".
     *
     * This request holds the parameters needed by the the plannedeventendpoint server.  After setting
     * any optional parameters, call the {@link ListPlannedEvent#execute()} method to invoke the
     * remote operation. <p> {@link ListPlannedEvent#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPlannedEvent() {
      super(Plannedeventendpoint.this, "GET", REST_PATH, null, com.wgappbackend.plannedeventendpoint.model.CollectionResponsePlannedEvent.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPlannedEvent setAlt(java.lang.String alt) {
      return (ListPlannedEvent) super.setAlt(alt);
    }

    @Override
    public ListPlannedEvent setFields(java.lang.String fields) {
      return (ListPlannedEvent) super.setFields(fields);
    }

    @Override
    public ListPlannedEvent setKey(java.lang.String key) {
      return (ListPlannedEvent) super.setKey(key);
    }

    @Override
    public ListPlannedEvent setOauthToken(java.lang.String oauthToken) {
      return (ListPlannedEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPlannedEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPlannedEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPlannedEvent setQuotaUser(java.lang.String quotaUser) {
      return (ListPlannedEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPlannedEvent setUserIp(java.lang.String userIp) {
      return (ListPlannedEvent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPlannedEvent setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPlannedEvent setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPlannedEvent set(String parameterName, Object value) {
      return (ListPlannedEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePlannedEvent".
   *
   * This request holds the parameters needed by the plannedeventendpoint server.  After setting any
   * optional parameters, call the {@link RemovePlannedEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePlannedEvent removePlannedEvent(java.lang.Long id) throws java.io.IOException {
    RemovePlannedEvent result = new RemovePlannedEvent(id);
    initialize(result);
    return result;
  }

  public class RemovePlannedEvent extends PlannedeventendpointRequest<Void> {

    private static final String REST_PATH = "plannedevent/{id}";

    /**
     * Create a request for the method "removePlannedEvent".
     *
     * This request holds the parameters needed by the the plannedeventendpoint server.  After setting
     * any optional parameters, call the {@link RemovePlannedEvent#execute()} method to invoke the
     * remote operation. <p> {@link RemovePlannedEvent#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePlannedEvent(java.lang.Long id) {
      super(Plannedeventendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePlannedEvent setAlt(java.lang.String alt) {
      return (RemovePlannedEvent) super.setAlt(alt);
    }

    @Override
    public RemovePlannedEvent setFields(java.lang.String fields) {
      return (RemovePlannedEvent) super.setFields(fields);
    }

    @Override
    public RemovePlannedEvent setKey(java.lang.String key) {
      return (RemovePlannedEvent) super.setKey(key);
    }

    @Override
    public RemovePlannedEvent setOauthToken(java.lang.String oauthToken) {
      return (RemovePlannedEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePlannedEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePlannedEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePlannedEvent setQuotaUser(java.lang.String quotaUser) {
      return (RemovePlannedEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePlannedEvent setUserIp(java.lang.String userIp) {
      return (RemovePlannedEvent) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePlannedEvent setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePlannedEvent set(String parameterName, Object value) {
      return (RemovePlannedEvent) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePlannedEvent".
   *
   * This request holds the parameters needed by the plannedeventendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePlannedEvent#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.plannedeventendpoint.model.PlannedEvent}
   * @return the request
   */
  public UpdatePlannedEvent updatePlannedEvent(com.wgappbackend.plannedeventendpoint.model.PlannedEvent content) throws java.io.IOException {
    UpdatePlannedEvent result = new UpdatePlannedEvent(content);
    initialize(result);
    return result;
  }

  public class UpdatePlannedEvent extends PlannedeventendpointRequest<com.wgappbackend.plannedeventendpoint.model.PlannedEvent> {

    private static final String REST_PATH = "plannedevent";

    /**
     * Create a request for the method "updatePlannedEvent".
     *
     * This request holds the parameters needed by the the plannedeventendpoint server.  After setting
     * any optional parameters, call the {@link UpdatePlannedEvent#execute()} method to invoke the
     * remote operation. <p> {@link UpdatePlannedEvent#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.plannedeventendpoint.model.PlannedEvent}
     * @since 1.13
     */
    protected UpdatePlannedEvent(com.wgappbackend.plannedeventendpoint.model.PlannedEvent content) {
      super(Plannedeventendpoint.this, "PUT", REST_PATH, content, com.wgappbackend.plannedeventendpoint.model.PlannedEvent.class);
    }

    @Override
    public UpdatePlannedEvent setAlt(java.lang.String alt) {
      return (UpdatePlannedEvent) super.setAlt(alt);
    }

    @Override
    public UpdatePlannedEvent setFields(java.lang.String fields) {
      return (UpdatePlannedEvent) super.setFields(fields);
    }

    @Override
    public UpdatePlannedEvent setKey(java.lang.String key) {
      return (UpdatePlannedEvent) super.setKey(key);
    }

    @Override
    public UpdatePlannedEvent setOauthToken(java.lang.String oauthToken) {
      return (UpdatePlannedEvent) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePlannedEvent setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePlannedEvent) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePlannedEvent setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePlannedEvent) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePlannedEvent setUserIp(java.lang.String userIp) {
      return (UpdatePlannedEvent) super.setUserIp(userIp);
    }

    @Override
    public UpdatePlannedEvent set(String parameterName, Object value) {
      return (UpdatePlannedEvent) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Plannedeventendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Plannedeventendpoint}. */
    @Override
    public Plannedeventendpoint build() {
      return new Plannedeventendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PlannedeventendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPlannedeventendpointRequestInitializer(
        PlannedeventendpointRequestInitializer plannedeventendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(plannedeventendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
