/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-07-08 17:28:43 UTC)
 * on 2016-09-25 at 17:25:05 UTC 
 * Modify at your own risk.
 */

package com.wgappbackend.plannedeventendpoint.model;

/**
 * Model definition for PlannedEvent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the plannedeventendpoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PlannedEvent extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime eventDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Resident resident;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime submissionDate;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public PlannedEvent setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getEventDate() {
    return eventDate;
  }

  /**
   * @param eventDate eventDate or {@code null} for none
   */
  public PlannedEvent setEventDate(com.google.api.client.util.DateTime eventDate) {
    this.eventDate = eventDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public PlannedEvent setId(java.lang.Integer id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Resident getResident() {
    return resident;
  }

  /**
   * @param resident resident or {@code null} for none
   */
  public PlannedEvent setResident(Resident resident) {
    this.resident = resident;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getSubmissionDate() {
    return submissionDate;
  }

  /**
   * @param submissionDate submissionDate or {@code null} for none
   */
  public PlannedEvent setSubmissionDate(com.google.api.client.util.DateTime submissionDate) {
    this.submissionDate = submissionDate;
    return this;
  }

  @Override
  public PlannedEvent set(String fieldName, Object value) {
    return (PlannedEvent) super.set(fieldName, value);
  }

  @Override
  public PlannedEvent clone() {
    return (PlannedEvent) super.clone();
  }

}
