/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-07-08 17:28:43 UTC)
 * on 2016-09-25 at 17:26:12 UTC 
 * Modify at your own risk.
 */

package com.wgappbackend.managerendpoint;

/**
 * Service definition for Managerendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ManagerendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Managerendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the managerendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "managerendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Managerendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Managerendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getManager".
   *
   * This request holds the parameters needed by the managerendpoint server.  After setting any
   * optional parameters, call the {@link GetManager#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetManager getManager(java.lang.Long id) throws java.io.IOException {
    GetManager result = new GetManager(id);
    initialize(result);
    return result;
  }

  public class GetManager extends ManagerendpointRequest<com.wgappbackend.managerendpoint.model.Manager> {

    private static final String REST_PATH = "manager/{id}";

    /**
     * Create a request for the method "getManager".
     *
     * This request holds the parameters needed by the the managerendpoint server.  After setting any
     * optional parameters, call the {@link GetManager#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetManager#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetManager(java.lang.Long id) {
      super(Managerendpoint.this, "GET", REST_PATH, null, com.wgappbackend.managerendpoint.model.Manager.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetManager setAlt(java.lang.String alt) {
      return (GetManager) super.setAlt(alt);
    }

    @Override
    public GetManager setFields(java.lang.String fields) {
      return (GetManager) super.setFields(fields);
    }

    @Override
    public GetManager setKey(java.lang.String key) {
      return (GetManager) super.setKey(key);
    }

    @Override
    public GetManager setOauthToken(java.lang.String oauthToken) {
      return (GetManager) super.setOauthToken(oauthToken);
    }

    @Override
    public GetManager setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetManager) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetManager setQuotaUser(java.lang.String quotaUser) {
      return (GetManager) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetManager setUserIp(java.lang.String userIp) {
      return (GetManager) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetManager setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetManager set(String parameterName, Object value) {
      return (GetManager) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertManager".
   *
   * This request holds the parameters needed by the managerendpoint server.  After setting any
   * optional parameters, call the {@link InsertManager#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.managerendpoint.model.Manager}
   * @return the request
   */
  public InsertManager insertManager(com.wgappbackend.managerendpoint.model.Manager content) throws java.io.IOException {
    InsertManager result = new InsertManager(content);
    initialize(result);
    return result;
  }

  public class InsertManager extends ManagerendpointRequest<com.wgappbackend.managerendpoint.model.Manager> {

    private static final String REST_PATH = "manager";

    /**
     * Create a request for the method "insertManager".
     *
     * This request holds the parameters needed by the the managerendpoint server.  After setting any
     * optional parameters, call the {@link InsertManager#execute()} method to invoke the remote
     * operation. <p> {@link InsertManager#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.managerendpoint.model.Manager}
     * @since 1.13
     */
    protected InsertManager(com.wgappbackend.managerendpoint.model.Manager content) {
      super(Managerendpoint.this, "POST", REST_PATH, content, com.wgappbackend.managerendpoint.model.Manager.class);
    }

    @Override
    public InsertManager setAlt(java.lang.String alt) {
      return (InsertManager) super.setAlt(alt);
    }

    @Override
    public InsertManager setFields(java.lang.String fields) {
      return (InsertManager) super.setFields(fields);
    }

    @Override
    public InsertManager setKey(java.lang.String key) {
      return (InsertManager) super.setKey(key);
    }

    @Override
    public InsertManager setOauthToken(java.lang.String oauthToken) {
      return (InsertManager) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertManager setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertManager) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertManager setQuotaUser(java.lang.String quotaUser) {
      return (InsertManager) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertManager setUserIp(java.lang.String userIp) {
      return (InsertManager) super.setUserIp(userIp);
    }

    @Override
    public InsertManager set(String parameterName, Object value) {
      return (InsertManager) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listManager".
   *
   * This request holds the parameters needed by the managerendpoint server.  After setting any
   * optional parameters, call the {@link ListManager#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListManager listManager() throws java.io.IOException {
    ListManager result = new ListManager();
    initialize(result);
    return result;
  }

  public class ListManager extends ManagerendpointRequest<com.wgappbackend.managerendpoint.model.CollectionResponseManager> {

    private static final String REST_PATH = "manager";

    /**
     * Create a request for the method "listManager".
     *
     * This request holds the parameters needed by the the managerendpoint server.  After setting any
     * optional parameters, call the {@link ListManager#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListManager#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListManager() {
      super(Managerendpoint.this, "GET", REST_PATH, null, com.wgappbackend.managerendpoint.model.CollectionResponseManager.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListManager setAlt(java.lang.String alt) {
      return (ListManager) super.setAlt(alt);
    }

    @Override
    public ListManager setFields(java.lang.String fields) {
      return (ListManager) super.setFields(fields);
    }

    @Override
    public ListManager setKey(java.lang.String key) {
      return (ListManager) super.setKey(key);
    }

    @Override
    public ListManager setOauthToken(java.lang.String oauthToken) {
      return (ListManager) super.setOauthToken(oauthToken);
    }

    @Override
    public ListManager setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListManager) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListManager setQuotaUser(java.lang.String quotaUser) {
      return (ListManager) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListManager setUserIp(java.lang.String userIp) {
      return (ListManager) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListManager setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListManager setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListManager set(String parameterName, Object value) {
      return (ListManager) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeManager".
   *
   * This request holds the parameters needed by the managerendpoint server.  After setting any
   * optional parameters, call the {@link RemoveManager#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveManager removeManager(java.lang.Long id) throws java.io.IOException {
    RemoveManager result = new RemoveManager(id);
    initialize(result);
    return result;
  }

  public class RemoveManager extends ManagerendpointRequest<Void> {

    private static final String REST_PATH = "manager/{id}";

    /**
     * Create a request for the method "removeManager".
     *
     * This request holds the parameters needed by the the managerendpoint server.  After setting any
     * optional parameters, call the {@link RemoveManager#execute()} method to invoke the remote
     * operation. <p> {@link RemoveManager#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveManager(java.lang.Long id) {
      super(Managerendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveManager setAlt(java.lang.String alt) {
      return (RemoveManager) super.setAlt(alt);
    }

    @Override
    public RemoveManager setFields(java.lang.String fields) {
      return (RemoveManager) super.setFields(fields);
    }

    @Override
    public RemoveManager setKey(java.lang.String key) {
      return (RemoveManager) super.setKey(key);
    }

    @Override
    public RemoveManager setOauthToken(java.lang.String oauthToken) {
      return (RemoveManager) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveManager setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveManager) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveManager setQuotaUser(java.lang.String quotaUser) {
      return (RemoveManager) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveManager setUserIp(java.lang.String userIp) {
      return (RemoveManager) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveManager setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveManager set(String parameterName, Object value) {
      return (RemoveManager) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateManager".
   *
   * This request holds the parameters needed by the managerendpoint server.  After setting any
   * optional parameters, call the {@link UpdateManager#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.managerendpoint.model.Manager}
   * @return the request
   */
  public UpdateManager updateManager(com.wgappbackend.managerendpoint.model.Manager content) throws java.io.IOException {
    UpdateManager result = new UpdateManager(content);
    initialize(result);
    return result;
  }

  public class UpdateManager extends ManagerendpointRequest<com.wgappbackend.managerendpoint.model.Manager> {

    private static final String REST_PATH = "manager";

    /**
     * Create a request for the method "updateManager".
     *
     * This request holds the parameters needed by the the managerendpoint server.  After setting any
     * optional parameters, call the {@link UpdateManager#execute()} method to invoke the remote
     * operation. <p> {@link UpdateManager#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.managerendpoint.model.Manager}
     * @since 1.13
     */
    protected UpdateManager(com.wgappbackend.managerendpoint.model.Manager content) {
      super(Managerendpoint.this, "PUT", REST_PATH, content, com.wgappbackend.managerendpoint.model.Manager.class);
    }

    @Override
    public UpdateManager setAlt(java.lang.String alt) {
      return (UpdateManager) super.setAlt(alt);
    }

    @Override
    public UpdateManager setFields(java.lang.String fields) {
      return (UpdateManager) super.setFields(fields);
    }

    @Override
    public UpdateManager setKey(java.lang.String key) {
      return (UpdateManager) super.setKey(key);
    }

    @Override
    public UpdateManager setOauthToken(java.lang.String oauthToken) {
      return (UpdateManager) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateManager setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateManager) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateManager setQuotaUser(java.lang.String quotaUser) {
      return (UpdateManager) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateManager setUserIp(java.lang.String userIp) {
      return (UpdateManager) super.setUserIp(userIp);
    }

    @Override
    public UpdateManager set(String parameterName, Object value) {
      return (UpdateManager) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Managerendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Managerendpoint}. */
    @Override
    public Managerendpoint build() {
      return new Managerendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ManagerendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setManagerendpointRequestInitializer(
        ManagerendpointRequestInitializer managerendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(managerendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
