/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-07-08 17:28:43 UTC)
 * on 2016-09-25 at 17:26:28 UTC 
 * Modify at your own risk.
 */

package com.wgappbackend.buyingendpoint;

/**
 * Service definition for Buyingendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link BuyingendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Buyingendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the buyingendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "buyingendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Buyingendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Buyingendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getBuying".
   *
   * This request holds the parameters needed by the buyingendpoint server.  After setting any
   * optional parameters, call the {@link GetBuying#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetBuying getBuying(java.lang.Long id) throws java.io.IOException {
    GetBuying result = new GetBuying(id);
    initialize(result);
    return result;
  }

  public class GetBuying extends BuyingendpointRequest<com.wgappbackend.buyingendpoint.model.Buying> {

    private static final String REST_PATH = "buying/{id}";

    /**
     * Create a request for the method "getBuying".
     *
     * This request holds the parameters needed by the the buyingendpoint server.  After setting any
     * optional parameters, call the {@link GetBuying#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetBuying#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetBuying(java.lang.Long id) {
      super(Buyingendpoint.this, "GET", REST_PATH, null, com.wgappbackend.buyingendpoint.model.Buying.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetBuying setAlt(java.lang.String alt) {
      return (GetBuying) super.setAlt(alt);
    }

    @Override
    public GetBuying setFields(java.lang.String fields) {
      return (GetBuying) super.setFields(fields);
    }

    @Override
    public GetBuying setKey(java.lang.String key) {
      return (GetBuying) super.setKey(key);
    }

    @Override
    public GetBuying setOauthToken(java.lang.String oauthToken) {
      return (GetBuying) super.setOauthToken(oauthToken);
    }

    @Override
    public GetBuying setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetBuying) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetBuying setQuotaUser(java.lang.String quotaUser) {
      return (GetBuying) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetBuying setUserIp(java.lang.String userIp) {
      return (GetBuying) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetBuying setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetBuying set(String parameterName, Object value) {
      return (GetBuying) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertBuying".
   *
   * This request holds the parameters needed by the buyingendpoint server.  After setting any
   * optional parameters, call the {@link InsertBuying#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.buyingendpoint.model.Buying}
   * @return the request
   */
  public InsertBuying insertBuying(com.wgappbackend.buyingendpoint.model.Buying content) throws java.io.IOException {
    InsertBuying result = new InsertBuying(content);
    initialize(result);
    return result;
  }

  public class InsertBuying extends BuyingendpointRequest<com.wgappbackend.buyingendpoint.model.Buying> {

    private static final String REST_PATH = "buying";

    /**
     * Create a request for the method "insertBuying".
     *
     * This request holds the parameters needed by the the buyingendpoint server.  After setting any
     * optional parameters, call the {@link InsertBuying#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertBuying#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.buyingendpoint.model.Buying}
     * @since 1.13
     */
    protected InsertBuying(com.wgappbackend.buyingendpoint.model.Buying content) {
      super(Buyingendpoint.this, "POST", REST_PATH, content, com.wgappbackend.buyingendpoint.model.Buying.class);
    }

    @Override
    public InsertBuying setAlt(java.lang.String alt) {
      return (InsertBuying) super.setAlt(alt);
    }

    @Override
    public InsertBuying setFields(java.lang.String fields) {
      return (InsertBuying) super.setFields(fields);
    }

    @Override
    public InsertBuying setKey(java.lang.String key) {
      return (InsertBuying) super.setKey(key);
    }

    @Override
    public InsertBuying setOauthToken(java.lang.String oauthToken) {
      return (InsertBuying) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertBuying setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertBuying) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertBuying setQuotaUser(java.lang.String quotaUser) {
      return (InsertBuying) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertBuying setUserIp(java.lang.String userIp) {
      return (InsertBuying) super.setUserIp(userIp);
    }

    @Override
    public InsertBuying set(String parameterName, Object value) {
      return (InsertBuying) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listBuying".
   *
   * This request holds the parameters needed by the buyingendpoint server.  After setting any
   * optional parameters, call the {@link ListBuying#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListBuying listBuying() throws java.io.IOException {
    ListBuying result = new ListBuying();
    initialize(result);
    return result;
  }

  public class ListBuying extends BuyingendpointRequest<com.wgappbackend.buyingendpoint.model.CollectionResponseBuying> {

    private static final String REST_PATH = "buying";

    /**
     * Create a request for the method "listBuying".
     *
     * This request holds the parameters needed by the the buyingendpoint server.  After setting any
     * optional parameters, call the {@link ListBuying#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListBuying#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListBuying() {
      super(Buyingendpoint.this, "GET", REST_PATH, null, com.wgappbackend.buyingendpoint.model.CollectionResponseBuying.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListBuying setAlt(java.lang.String alt) {
      return (ListBuying) super.setAlt(alt);
    }

    @Override
    public ListBuying setFields(java.lang.String fields) {
      return (ListBuying) super.setFields(fields);
    }

    @Override
    public ListBuying setKey(java.lang.String key) {
      return (ListBuying) super.setKey(key);
    }

    @Override
    public ListBuying setOauthToken(java.lang.String oauthToken) {
      return (ListBuying) super.setOauthToken(oauthToken);
    }

    @Override
    public ListBuying setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListBuying) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListBuying setQuotaUser(java.lang.String quotaUser) {
      return (ListBuying) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListBuying setUserIp(java.lang.String userIp) {
      return (ListBuying) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListBuying setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListBuying setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListBuying set(String parameterName, Object value) {
      return (ListBuying) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeBuying".
   *
   * This request holds the parameters needed by the buyingendpoint server.  After setting any
   * optional parameters, call the {@link RemoveBuying#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveBuying removeBuying(java.lang.Long id) throws java.io.IOException {
    RemoveBuying result = new RemoveBuying(id);
    initialize(result);
    return result;
  }

  public class RemoveBuying extends BuyingendpointRequest<Void> {

    private static final String REST_PATH = "buying/{id}";

    /**
     * Create a request for the method "removeBuying".
     *
     * This request holds the parameters needed by the the buyingendpoint server.  After setting any
     * optional parameters, call the {@link RemoveBuying#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveBuying#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveBuying(java.lang.Long id) {
      super(Buyingendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveBuying setAlt(java.lang.String alt) {
      return (RemoveBuying) super.setAlt(alt);
    }

    @Override
    public RemoveBuying setFields(java.lang.String fields) {
      return (RemoveBuying) super.setFields(fields);
    }

    @Override
    public RemoveBuying setKey(java.lang.String key) {
      return (RemoveBuying) super.setKey(key);
    }

    @Override
    public RemoveBuying setOauthToken(java.lang.String oauthToken) {
      return (RemoveBuying) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveBuying setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveBuying) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveBuying setQuotaUser(java.lang.String quotaUser) {
      return (RemoveBuying) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveBuying setUserIp(java.lang.String userIp) {
      return (RemoveBuying) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveBuying setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveBuying set(String parameterName, Object value) {
      return (RemoveBuying) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateBuying".
   *
   * This request holds the parameters needed by the buyingendpoint server.  After setting any
   * optional parameters, call the {@link UpdateBuying#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.buyingendpoint.model.Buying}
   * @return the request
   */
  public UpdateBuying updateBuying(com.wgappbackend.buyingendpoint.model.Buying content) throws java.io.IOException {
    UpdateBuying result = new UpdateBuying(content);
    initialize(result);
    return result;
  }

  public class UpdateBuying extends BuyingendpointRequest<com.wgappbackend.buyingendpoint.model.Buying> {

    private static final String REST_PATH = "buying";

    /**
     * Create a request for the method "updateBuying".
     *
     * This request holds the parameters needed by the the buyingendpoint server.  After setting any
     * optional parameters, call the {@link UpdateBuying#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateBuying#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.buyingendpoint.model.Buying}
     * @since 1.13
     */
    protected UpdateBuying(com.wgappbackend.buyingendpoint.model.Buying content) {
      super(Buyingendpoint.this, "PUT", REST_PATH, content, com.wgappbackend.buyingendpoint.model.Buying.class);
    }

    @Override
    public UpdateBuying setAlt(java.lang.String alt) {
      return (UpdateBuying) super.setAlt(alt);
    }

    @Override
    public UpdateBuying setFields(java.lang.String fields) {
      return (UpdateBuying) super.setFields(fields);
    }

    @Override
    public UpdateBuying setKey(java.lang.String key) {
      return (UpdateBuying) super.setKey(key);
    }

    @Override
    public UpdateBuying setOauthToken(java.lang.String oauthToken) {
      return (UpdateBuying) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateBuying setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateBuying) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateBuying setQuotaUser(java.lang.String quotaUser) {
      return (UpdateBuying) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateBuying setUserIp(java.lang.String userIp) {
      return (UpdateBuying) super.setUserIp(userIp);
    }

    @Override
    public UpdateBuying set(String parameterName, Object value) {
      return (UpdateBuying) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Buyingendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Buyingendpoint}. */
    @Override
    public Buyingendpoint build() {
      return new Buyingendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link BuyingendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setBuyingendpointRequestInitializer(
        BuyingendpointRequestInitializer buyingendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(buyingendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
