/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-07-08 17:28:43 UTC)
 * on 2016-09-25 at 17:25:13 UTC 
 * Modify at your own risk.
 */

package com.wgappbackend.alimentgroupendpoint;

/**
 * Service definition for Alimentgroupendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AlimentgroupendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Alimentgroupendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the alimentgroupendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "alimentgroupendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Alimentgroupendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Alimentgroupendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAlimentGroup".
   *
   * This request holds the parameters needed by the alimentgroupendpoint server.  After setting any
   * optional parameters, call the {@link GetAlimentGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetAlimentGroup getAlimentGroup(java.lang.Long id) throws java.io.IOException {
    GetAlimentGroup result = new GetAlimentGroup(id);
    initialize(result);
    return result;
  }

  public class GetAlimentGroup extends AlimentgroupendpointRequest<com.wgappbackend.alimentgroupendpoint.model.AlimentGroup> {

    private static final String REST_PATH = "alimentgroup/{id}";

    /**
     * Create a request for the method "getAlimentGroup".
     *
     * This request holds the parameters needed by the the alimentgroupendpoint server.  After setting
     * any optional parameters, call the {@link GetAlimentGroup#execute()} method to invoke the remote
     * operation. <p> {@link GetAlimentGroup#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAlimentGroup(java.lang.Long id) {
      super(Alimentgroupendpoint.this, "GET", REST_PATH, null, com.wgappbackend.alimentgroupendpoint.model.AlimentGroup.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAlimentGroup setAlt(java.lang.String alt) {
      return (GetAlimentGroup) super.setAlt(alt);
    }

    @Override
    public GetAlimentGroup setFields(java.lang.String fields) {
      return (GetAlimentGroup) super.setFields(fields);
    }

    @Override
    public GetAlimentGroup setKey(java.lang.String key) {
      return (GetAlimentGroup) super.setKey(key);
    }

    @Override
    public GetAlimentGroup setOauthToken(java.lang.String oauthToken) {
      return (GetAlimentGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAlimentGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAlimentGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAlimentGroup setQuotaUser(java.lang.String quotaUser) {
      return (GetAlimentGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAlimentGroup setUserIp(java.lang.String userIp) {
      return (GetAlimentGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetAlimentGroup setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAlimentGroup set(String parameterName, Object value) {
      return (GetAlimentGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAlimentGroup".
   *
   * This request holds the parameters needed by the alimentgroupendpoint server.  After setting any
   * optional parameters, call the {@link InsertAlimentGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.alimentgroupendpoint.model.AlimentGroup}
   * @return the request
   */
  public InsertAlimentGroup insertAlimentGroup(com.wgappbackend.alimentgroupendpoint.model.AlimentGroup content) throws java.io.IOException {
    InsertAlimentGroup result = new InsertAlimentGroup(content);
    initialize(result);
    return result;
  }

  public class InsertAlimentGroup extends AlimentgroupendpointRequest<com.wgappbackend.alimentgroupendpoint.model.AlimentGroup> {

    private static final String REST_PATH = "alimentgroup";

    /**
     * Create a request for the method "insertAlimentGroup".
     *
     * This request holds the parameters needed by the the alimentgroupendpoint server.  After setting
     * any optional parameters, call the {@link InsertAlimentGroup#execute()} method to invoke the
     * remote operation. <p> {@link InsertAlimentGroup#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.alimentgroupendpoint.model.AlimentGroup}
     * @since 1.13
     */
    protected InsertAlimentGroup(com.wgappbackend.alimentgroupendpoint.model.AlimentGroup content) {
      super(Alimentgroupendpoint.this, "POST", REST_PATH, content, com.wgappbackend.alimentgroupendpoint.model.AlimentGroup.class);
    }

    @Override
    public InsertAlimentGroup setAlt(java.lang.String alt) {
      return (InsertAlimentGroup) super.setAlt(alt);
    }

    @Override
    public InsertAlimentGroup setFields(java.lang.String fields) {
      return (InsertAlimentGroup) super.setFields(fields);
    }

    @Override
    public InsertAlimentGroup setKey(java.lang.String key) {
      return (InsertAlimentGroup) super.setKey(key);
    }

    @Override
    public InsertAlimentGroup setOauthToken(java.lang.String oauthToken) {
      return (InsertAlimentGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAlimentGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAlimentGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAlimentGroup setQuotaUser(java.lang.String quotaUser) {
      return (InsertAlimentGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAlimentGroup setUserIp(java.lang.String userIp) {
      return (InsertAlimentGroup) super.setUserIp(userIp);
    }

    @Override
    public InsertAlimentGroup set(String parameterName, Object value) {
      return (InsertAlimentGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAlimentGroup".
   *
   * This request holds the parameters needed by the alimentgroupendpoint server.  After setting any
   * optional parameters, call the {@link ListAlimentGroup#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAlimentGroup listAlimentGroup() throws java.io.IOException {
    ListAlimentGroup result = new ListAlimentGroup();
    initialize(result);
    return result;
  }

  public class ListAlimentGroup extends AlimentgroupendpointRequest<com.wgappbackend.alimentgroupendpoint.model.CollectionResponseAlimentGroup> {

    private static final String REST_PATH = "alimentgroup";

    /**
     * Create a request for the method "listAlimentGroup".
     *
     * This request holds the parameters needed by the the alimentgroupendpoint server.  After setting
     * any optional parameters, call the {@link ListAlimentGroup#execute()} method to invoke the
     * remote operation. <p> {@link ListAlimentGroup#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAlimentGroup() {
      super(Alimentgroupendpoint.this, "GET", REST_PATH, null, com.wgappbackend.alimentgroupendpoint.model.CollectionResponseAlimentGroup.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAlimentGroup setAlt(java.lang.String alt) {
      return (ListAlimentGroup) super.setAlt(alt);
    }

    @Override
    public ListAlimentGroup setFields(java.lang.String fields) {
      return (ListAlimentGroup) super.setFields(fields);
    }

    @Override
    public ListAlimentGroup setKey(java.lang.String key) {
      return (ListAlimentGroup) super.setKey(key);
    }

    @Override
    public ListAlimentGroup setOauthToken(java.lang.String oauthToken) {
      return (ListAlimentGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAlimentGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAlimentGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAlimentGroup setQuotaUser(java.lang.String quotaUser) {
      return (ListAlimentGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAlimentGroup setUserIp(java.lang.String userIp) {
      return (ListAlimentGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAlimentGroup setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAlimentGroup setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAlimentGroup set(String parameterName, Object value) {
      return (ListAlimentGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAlimentGroup".
   *
   * This request holds the parameters needed by the alimentgroupendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAlimentGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAlimentGroup removeAlimentGroup(java.lang.Long id) throws java.io.IOException {
    RemoveAlimentGroup result = new RemoveAlimentGroup(id);
    initialize(result);
    return result;
  }

  public class RemoveAlimentGroup extends AlimentgroupendpointRequest<Void> {

    private static final String REST_PATH = "alimentgroup/{id}";

    /**
     * Create a request for the method "removeAlimentGroup".
     *
     * This request holds the parameters needed by the the alimentgroupendpoint server.  After setting
     * any optional parameters, call the {@link RemoveAlimentGroup#execute()} method to invoke the
     * remote operation. <p> {@link RemoveAlimentGroup#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAlimentGroup(java.lang.Long id) {
      super(Alimentgroupendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAlimentGroup setAlt(java.lang.String alt) {
      return (RemoveAlimentGroup) super.setAlt(alt);
    }

    @Override
    public RemoveAlimentGroup setFields(java.lang.String fields) {
      return (RemoveAlimentGroup) super.setFields(fields);
    }

    @Override
    public RemoveAlimentGroup setKey(java.lang.String key) {
      return (RemoveAlimentGroup) super.setKey(key);
    }

    @Override
    public RemoveAlimentGroup setOauthToken(java.lang.String oauthToken) {
      return (RemoveAlimentGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAlimentGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAlimentGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAlimentGroup setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAlimentGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAlimentGroup setUserIp(java.lang.String userIp) {
      return (RemoveAlimentGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveAlimentGroup setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAlimentGroup set(String parameterName, Object value) {
      return (RemoveAlimentGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAlimentGroup".
   *
   * This request holds the parameters needed by the alimentgroupendpoint server.  After setting any
   * optional parameters, call the {@link UpdateAlimentGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.alimentgroupendpoint.model.AlimentGroup}
   * @return the request
   */
  public UpdateAlimentGroup updateAlimentGroup(com.wgappbackend.alimentgroupendpoint.model.AlimentGroup content) throws java.io.IOException {
    UpdateAlimentGroup result = new UpdateAlimentGroup(content);
    initialize(result);
    return result;
  }

  public class UpdateAlimentGroup extends AlimentgroupendpointRequest<com.wgappbackend.alimentgroupendpoint.model.AlimentGroup> {

    private static final String REST_PATH = "alimentgroup";

    /**
     * Create a request for the method "updateAlimentGroup".
     *
     * This request holds the parameters needed by the the alimentgroupendpoint server.  After setting
     * any optional parameters, call the {@link UpdateAlimentGroup#execute()} method to invoke the
     * remote operation. <p> {@link UpdateAlimentGroup#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.alimentgroupendpoint.model.AlimentGroup}
     * @since 1.13
     */
    protected UpdateAlimentGroup(com.wgappbackend.alimentgroupendpoint.model.AlimentGroup content) {
      super(Alimentgroupendpoint.this, "PUT", REST_PATH, content, com.wgappbackend.alimentgroupendpoint.model.AlimentGroup.class);
    }

    @Override
    public UpdateAlimentGroup setAlt(java.lang.String alt) {
      return (UpdateAlimentGroup) super.setAlt(alt);
    }

    @Override
    public UpdateAlimentGroup setFields(java.lang.String fields) {
      return (UpdateAlimentGroup) super.setFields(fields);
    }

    @Override
    public UpdateAlimentGroup setKey(java.lang.String key) {
      return (UpdateAlimentGroup) super.setKey(key);
    }

    @Override
    public UpdateAlimentGroup setOauthToken(java.lang.String oauthToken) {
      return (UpdateAlimentGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAlimentGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAlimentGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAlimentGroup setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAlimentGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAlimentGroup setUserIp(java.lang.String userIp) {
      return (UpdateAlimentGroup) super.setUserIp(userIp);
    }

    @Override
    public UpdateAlimentGroup set(String parameterName, Object value) {
      return (UpdateAlimentGroup) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Alimentgroupendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Alimentgroupendpoint}. */
    @Override
    public Alimentgroupendpoint build() {
      return new Alimentgroupendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AlimentgroupendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAlimentgroupendpointRequestInitializer(
        AlimentgroupendpointRequestInitializer alimentgroupendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(alimentgroupendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
