/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-07-08 17:28:43 UTC)
 * on 2016-09-25 at 17:25:39 UTC 
 * Modify at your own risk.
 */

package com.wgappbackend.communeendpoint;

/**
 * Service definition for Communeendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CommuneendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Communeendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the communeendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "communeendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Communeendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Communeendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getCommune".
   *
   * This request holds the parameters needed by the communeendpoint server.  After setting any
   * optional parameters, call the {@link GetCommune#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetCommune getCommune(java.lang.Long id) throws java.io.IOException {
    GetCommune result = new GetCommune(id);
    initialize(result);
    return result;
  }

  public class GetCommune extends CommuneendpointRequest<com.wgappbackend.communeendpoint.model.Commune> {

    private static final String REST_PATH = "commune/{id}";

    /**
     * Create a request for the method "getCommune".
     *
     * This request holds the parameters needed by the the communeendpoint server.  After setting any
     * optional parameters, call the {@link GetCommune#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetCommune#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetCommune(java.lang.Long id) {
      super(Communeendpoint.this, "GET", REST_PATH, null, com.wgappbackend.communeendpoint.model.Commune.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetCommune setAlt(java.lang.String alt) {
      return (GetCommune) super.setAlt(alt);
    }

    @Override
    public GetCommune setFields(java.lang.String fields) {
      return (GetCommune) super.setFields(fields);
    }

    @Override
    public GetCommune setKey(java.lang.String key) {
      return (GetCommune) super.setKey(key);
    }

    @Override
    public GetCommune setOauthToken(java.lang.String oauthToken) {
      return (GetCommune) super.setOauthToken(oauthToken);
    }

    @Override
    public GetCommune setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetCommune) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetCommune setQuotaUser(java.lang.String quotaUser) {
      return (GetCommune) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetCommune setUserIp(java.lang.String userIp) {
      return (GetCommune) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetCommune setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetCommune set(String parameterName, Object value) {
      return (GetCommune) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertCommune".
   *
   * This request holds the parameters needed by the communeendpoint server.  After setting any
   * optional parameters, call the {@link InsertCommune#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.communeendpoint.model.Commune}
   * @return the request
   */
  public InsertCommune insertCommune(com.wgappbackend.communeendpoint.model.Commune content) throws java.io.IOException {
    InsertCommune result = new InsertCommune(content);
    initialize(result);
    return result;
  }

  public class InsertCommune extends CommuneendpointRequest<com.wgappbackend.communeendpoint.model.Commune> {

    private static final String REST_PATH = "commune";

    /**
     * Create a request for the method "insertCommune".
     *
     * This request holds the parameters needed by the the communeendpoint server.  After setting any
     * optional parameters, call the {@link InsertCommune#execute()} method to invoke the remote
     * operation. <p> {@link InsertCommune#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.communeendpoint.model.Commune}
     * @since 1.13
     */
    protected InsertCommune(com.wgappbackend.communeendpoint.model.Commune content) {
      super(Communeendpoint.this, "POST", REST_PATH, content, com.wgappbackend.communeendpoint.model.Commune.class);
    }

    @Override
    public InsertCommune setAlt(java.lang.String alt) {
      return (InsertCommune) super.setAlt(alt);
    }

    @Override
    public InsertCommune setFields(java.lang.String fields) {
      return (InsertCommune) super.setFields(fields);
    }

    @Override
    public InsertCommune setKey(java.lang.String key) {
      return (InsertCommune) super.setKey(key);
    }

    @Override
    public InsertCommune setOauthToken(java.lang.String oauthToken) {
      return (InsertCommune) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertCommune setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertCommune) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertCommune setQuotaUser(java.lang.String quotaUser) {
      return (InsertCommune) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertCommune setUserIp(java.lang.String userIp) {
      return (InsertCommune) super.setUserIp(userIp);
    }

    @Override
    public InsertCommune set(String parameterName, Object value) {
      return (InsertCommune) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listCommune".
   *
   * This request holds the parameters needed by the communeendpoint server.  After setting any
   * optional parameters, call the {@link ListCommune#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListCommune listCommune() throws java.io.IOException {
    ListCommune result = new ListCommune();
    initialize(result);
    return result;
  }

  public class ListCommune extends CommuneendpointRequest<com.wgappbackend.communeendpoint.model.CollectionResponseCommune> {

    private static final String REST_PATH = "commune";

    /**
     * Create a request for the method "listCommune".
     *
     * This request holds the parameters needed by the the communeendpoint server.  After setting any
     * optional parameters, call the {@link ListCommune#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListCommune#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListCommune() {
      super(Communeendpoint.this, "GET", REST_PATH, null, com.wgappbackend.communeendpoint.model.CollectionResponseCommune.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListCommune setAlt(java.lang.String alt) {
      return (ListCommune) super.setAlt(alt);
    }

    @Override
    public ListCommune setFields(java.lang.String fields) {
      return (ListCommune) super.setFields(fields);
    }

    @Override
    public ListCommune setKey(java.lang.String key) {
      return (ListCommune) super.setKey(key);
    }

    @Override
    public ListCommune setOauthToken(java.lang.String oauthToken) {
      return (ListCommune) super.setOauthToken(oauthToken);
    }

    @Override
    public ListCommune setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListCommune) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListCommune setQuotaUser(java.lang.String quotaUser) {
      return (ListCommune) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListCommune setUserIp(java.lang.String userIp) {
      return (ListCommune) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListCommune setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListCommune setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListCommune set(String parameterName, Object value) {
      return (ListCommune) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeCommune".
   *
   * This request holds the parameters needed by the communeendpoint server.  After setting any
   * optional parameters, call the {@link RemoveCommune#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveCommune removeCommune(java.lang.Long id) throws java.io.IOException {
    RemoveCommune result = new RemoveCommune(id);
    initialize(result);
    return result;
  }

  public class RemoveCommune extends CommuneendpointRequest<Void> {

    private static final String REST_PATH = "commune/{id}";

    /**
     * Create a request for the method "removeCommune".
     *
     * This request holds the parameters needed by the the communeendpoint server.  After setting any
     * optional parameters, call the {@link RemoveCommune#execute()} method to invoke the remote
     * operation. <p> {@link RemoveCommune#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveCommune(java.lang.Long id) {
      super(Communeendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveCommune setAlt(java.lang.String alt) {
      return (RemoveCommune) super.setAlt(alt);
    }

    @Override
    public RemoveCommune setFields(java.lang.String fields) {
      return (RemoveCommune) super.setFields(fields);
    }

    @Override
    public RemoveCommune setKey(java.lang.String key) {
      return (RemoveCommune) super.setKey(key);
    }

    @Override
    public RemoveCommune setOauthToken(java.lang.String oauthToken) {
      return (RemoveCommune) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveCommune setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveCommune) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveCommune setQuotaUser(java.lang.String quotaUser) {
      return (RemoveCommune) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveCommune setUserIp(java.lang.String userIp) {
      return (RemoveCommune) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveCommune setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveCommune set(String parameterName, Object value) {
      return (RemoveCommune) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateCommune".
   *
   * This request holds the parameters needed by the communeendpoint server.  After setting any
   * optional parameters, call the {@link UpdateCommune#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.communeendpoint.model.Commune}
   * @return the request
   */
  public UpdateCommune updateCommune(com.wgappbackend.communeendpoint.model.Commune content) throws java.io.IOException {
    UpdateCommune result = new UpdateCommune(content);
    initialize(result);
    return result;
  }

  public class UpdateCommune extends CommuneendpointRequest<com.wgappbackend.communeendpoint.model.Commune> {

    private static final String REST_PATH = "commune";

    /**
     * Create a request for the method "updateCommune".
     *
     * This request holds the parameters needed by the the communeendpoint server.  After setting any
     * optional parameters, call the {@link UpdateCommune#execute()} method to invoke the remote
     * operation. <p> {@link UpdateCommune#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.communeendpoint.model.Commune}
     * @since 1.13
     */
    protected UpdateCommune(com.wgappbackend.communeendpoint.model.Commune content) {
      super(Communeendpoint.this, "PUT", REST_PATH, content, com.wgappbackend.communeendpoint.model.Commune.class);
    }

    @Override
    public UpdateCommune setAlt(java.lang.String alt) {
      return (UpdateCommune) super.setAlt(alt);
    }

    @Override
    public UpdateCommune setFields(java.lang.String fields) {
      return (UpdateCommune) super.setFields(fields);
    }

    @Override
    public UpdateCommune setKey(java.lang.String key) {
      return (UpdateCommune) super.setKey(key);
    }

    @Override
    public UpdateCommune setOauthToken(java.lang.String oauthToken) {
      return (UpdateCommune) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateCommune setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateCommune) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateCommune setQuotaUser(java.lang.String quotaUser) {
      return (UpdateCommune) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateCommune setUserIp(java.lang.String userIp) {
      return (UpdateCommune) super.setUserIp(userIp);
    }

    @Override
    public UpdateCommune set(String parameterName, Object value) {
      return (UpdateCommune) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Communeendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Communeendpoint}. */
    @Override
    public Communeendpoint build() {
      return new Communeendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CommuneendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCommuneendpointRequestInitializer(
        CommuneendpointRequestInitializer communeendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(communeendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
