/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-07-08 17:28:43 UTC)
 * on 2016-09-25 at 17:25:53 UTC 
 * Modify at your own risk.
 */

package com.wgappbackend.residentendpoint;

/**
 * Service definition for Residentendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ResidentendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Residentendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.21.0 of the residentendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "residentendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Residentendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Residentendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getResident".
   *
   * This request holds the parameters needed by the residentendpoint server.  After setting any
   * optional parameters, call the {@link GetResident#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetResident getResident(java.lang.Long id) throws java.io.IOException {
    GetResident result = new GetResident(id);
    initialize(result);
    return result;
  }

  public class GetResident extends ResidentendpointRequest<com.wgappbackend.residentendpoint.model.Resident> {

    private static final String REST_PATH = "resident/{id}";

    /**
     * Create a request for the method "getResident".
     *
     * This request holds the parameters needed by the the residentendpoint server.  After setting any
     * optional parameters, call the {@link GetResident#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetResident#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetResident(java.lang.Long id) {
      super(Residentendpoint.this, "GET", REST_PATH, null, com.wgappbackend.residentendpoint.model.Resident.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetResident setAlt(java.lang.String alt) {
      return (GetResident) super.setAlt(alt);
    }

    @Override
    public GetResident setFields(java.lang.String fields) {
      return (GetResident) super.setFields(fields);
    }

    @Override
    public GetResident setKey(java.lang.String key) {
      return (GetResident) super.setKey(key);
    }

    @Override
    public GetResident setOauthToken(java.lang.String oauthToken) {
      return (GetResident) super.setOauthToken(oauthToken);
    }

    @Override
    public GetResident setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetResident) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetResident setQuotaUser(java.lang.String quotaUser) {
      return (GetResident) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetResident setUserIp(java.lang.String userIp) {
      return (GetResident) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetResident setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetResident set(String parameterName, Object value) {
      return (GetResident) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertResident".
   *
   * This request holds the parameters needed by the residentendpoint server.  After setting any
   * optional parameters, call the {@link InsertResident#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.residentendpoint.model.Resident}
   * @return the request
   */
  public InsertResident insertResident(com.wgappbackend.residentendpoint.model.Resident content) throws java.io.IOException {
    InsertResident result = new InsertResident(content);
    initialize(result);
    return result;
  }

  public class InsertResident extends ResidentendpointRequest<com.wgappbackend.residentendpoint.model.Resident> {

    private static final String REST_PATH = "resident";

    /**
     * Create a request for the method "insertResident".
     *
     * This request holds the parameters needed by the the residentendpoint server.  After setting any
     * optional parameters, call the {@link InsertResident#execute()} method to invoke the remote
     * operation. <p> {@link InsertResident#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.residentendpoint.model.Resident}
     * @since 1.13
     */
    protected InsertResident(com.wgappbackend.residentendpoint.model.Resident content) {
      super(Residentendpoint.this, "POST", REST_PATH, content, com.wgappbackend.residentendpoint.model.Resident.class);
    }

    @Override
    public InsertResident setAlt(java.lang.String alt) {
      return (InsertResident) super.setAlt(alt);
    }

    @Override
    public InsertResident setFields(java.lang.String fields) {
      return (InsertResident) super.setFields(fields);
    }

    @Override
    public InsertResident setKey(java.lang.String key) {
      return (InsertResident) super.setKey(key);
    }

    @Override
    public InsertResident setOauthToken(java.lang.String oauthToken) {
      return (InsertResident) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertResident setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertResident) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertResident setQuotaUser(java.lang.String quotaUser) {
      return (InsertResident) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertResident setUserIp(java.lang.String userIp) {
      return (InsertResident) super.setUserIp(userIp);
    }

    @Override
    public InsertResident set(String parameterName, Object value) {
      return (InsertResident) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listResident".
   *
   * This request holds the parameters needed by the residentendpoint server.  After setting any
   * optional parameters, call the {@link ListResident#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListResident listResident() throws java.io.IOException {
    ListResident result = new ListResident();
    initialize(result);
    return result;
  }

  public class ListResident extends ResidentendpointRequest<com.wgappbackend.residentendpoint.model.CollectionResponseResident> {

    private static final String REST_PATH = "resident";

    /**
     * Create a request for the method "listResident".
     *
     * This request holds the parameters needed by the the residentendpoint server.  After setting any
     * optional parameters, call the {@link ListResident#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListResident#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListResident() {
      super(Residentendpoint.this, "GET", REST_PATH, null, com.wgappbackend.residentendpoint.model.CollectionResponseResident.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListResident setAlt(java.lang.String alt) {
      return (ListResident) super.setAlt(alt);
    }

    @Override
    public ListResident setFields(java.lang.String fields) {
      return (ListResident) super.setFields(fields);
    }

    @Override
    public ListResident setKey(java.lang.String key) {
      return (ListResident) super.setKey(key);
    }

    @Override
    public ListResident setOauthToken(java.lang.String oauthToken) {
      return (ListResident) super.setOauthToken(oauthToken);
    }

    @Override
    public ListResident setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListResident) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListResident setQuotaUser(java.lang.String quotaUser) {
      return (ListResident) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListResident setUserIp(java.lang.String userIp) {
      return (ListResident) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListResident setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListResident setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListResident set(String parameterName, Object value) {
      return (ListResident) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeResident".
   *
   * This request holds the parameters needed by the residentendpoint server.  After setting any
   * optional parameters, call the {@link RemoveResident#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveResident removeResident(java.lang.Long id) throws java.io.IOException {
    RemoveResident result = new RemoveResident(id);
    initialize(result);
    return result;
  }

  public class RemoveResident extends ResidentendpointRequest<Void> {

    private static final String REST_PATH = "resident/{id}";

    /**
     * Create a request for the method "removeResident".
     *
     * This request holds the parameters needed by the the residentendpoint server.  After setting any
     * optional parameters, call the {@link RemoveResident#execute()} method to invoke the remote
     * operation. <p> {@link RemoveResident#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveResident(java.lang.Long id) {
      super(Residentendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveResident setAlt(java.lang.String alt) {
      return (RemoveResident) super.setAlt(alt);
    }

    @Override
    public RemoveResident setFields(java.lang.String fields) {
      return (RemoveResident) super.setFields(fields);
    }

    @Override
    public RemoveResident setKey(java.lang.String key) {
      return (RemoveResident) super.setKey(key);
    }

    @Override
    public RemoveResident setOauthToken(java.lang.String oauthToken) {
      return (RemoveResident) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveResident setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveResident) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveResident setQuotaUser(java.lang.String quotaUser) {
      return (RemoveResident) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveResident setUserIp(java.lang.String userIp) {
      return (RemoveResident) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveResident setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveResident set(String parameterName, Object value) {
      return (RemoveResident) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateResident".
   *
   * This request holds the parameters needed by the residentendpoint server.  After setting any
   * optional parameters, call the {@link UpdateResident#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.wgappbackend.residentendpoint.model.Resident}
   * @return the request
   */
  public UpdateResident updateResident(com.wgappbackend.residentendpoint.model.Resident content) throws java.io.IOException {
    UpdateResident result = new UpdateResident(content);
    initialize(result);
    return result;
  }

  public class UpdateResident extends ResidentendpointRequest<com.wgappbackend.residentendpoint.model.Resident> {

    private static final String REST_PATH = "resident";

    /**
     * Create a request for the method "updateResident".
     *
     * This request holds the parameters needed by the the residentendpoint server.  After setting any
     * optional parameters, call the {@link UpdateResident#execute()} method to invoke the remote
     * operation. <p> {@link UpdateResident#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.wgappbackend.residentendpoint.model.Resident}
     * @since 1.13
     */
    protected UpdateResident(com.wgappbackend.residentendpoint.model.Resident content) {
      super(Residentendpoint.this, "PUT", REST_PATH, content, com.wgappbackend.residentendpoint.model.Resident.class);
    }

    @Override
    public UpdateResident setAlt(java.lang.String alt) {
      return (UpdateResident) super.setAlt(alt);
    }

    @Override
    public UpdateResident setFields(java.lang.String fields) {
      return (UpdateResident) super.setFields(fields);
    }

    @Override
    public UpdateResident setKey(java.lang.String key) {
      return (UpdateResident) super.setKey(key);
    }

    @Override
    public UpdateResident setOauthToken(java.lang.String oauthToken) {
      return (UpdateResident) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateResident setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateResident) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateResident setQuotaUser(java.lang.String quotaUser) {
      return (UpdateResident) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateResident setUserIp(java.lang.String userIp) {
      return (UpdateResident) super.setUserIp(userIp);
    }

    @Override
    public UpdateResident set(String parameterName, Object value) {
      return (UpdateResident) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Residentendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Residentendpoint}. */
    @Override
    public Residentendpoint build() {
      return new Residentendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ResidentendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setResidentendpointRequestInitializer(
        ResidentendpointRequestInitializer residentendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(residentendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
